version: "3"
services: 
  client:
    build: 
      context: ./client
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=http://server:4000
  server:
    build:
      context: ./server
    ports:
      - 4000:4000